### ISSUE TITLE
Demos: Verify and update demos

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/confidentialcontainers.org#3]
Recreate the demo here and update the documentation accordingly.

- [ ] CCv0 Operator Demo
  - User facing link: https://confidentialcontainers.org/docs/demos/ccv0-operator-demo/
  - Markdown: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/demos/ccv0-operator-demo.md
  - Once updated add a redirect link to the demo doc instead of the actual demo here:
  https://github.com/confidential-containers/confidential-containers/tree/main/demos/operator-demo

- [ ] SSH Demo
  - User facing link: https://confidentialcontainers.org/docs/demos/ssh-demo/
  - Markdown: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/demos/ssh-demo/index.md
  - Once updated add a redirect link to the demo doc from the confidentialcontainers.org instead of the actual demo here: https://github.com/confidential-containers/confidential-containers/tree/main/demos/ssh-demo

**Comment by fitzthum** [comment]
These demos are out of date and have been removed. Now we can put new demos in the examples section.
