### ISSUE TITLE
Update Guest Components Documentation

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/confidentialcontainers.org#4]
- [ ] Landing page:
    - Website URL: https://confidentialcontainers.org/docs/guest-components/
    - GH: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/guest-components/_index.md

- [ ] API Server Rest:
    - Website: https://confidentialcontainers.org/docs/guest-components/api-server-rest/
    - GH: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/guest-components/api-server-rest/_index.md

- [ ] Attestation Agent:
    - Website: https://confidentialcontainers.org/docs/guest-components/attestation-agent/
    - GH: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/guest-components/attestation-agent/_index.md

- [ ] CDH
    - Website: https://confidentialcontainers.org/docs/guest-components/confidential-data-hub/
    - GH: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/guest-components/confidential-data-hub/_index.md

- [ ] Image-RS
    - Website: https://confidentialcontainers.org/docs/guest-components/image-rs/
    - GH: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/guest-components/image-rs/_index.md

- [ ] OCICrypt-RS
    - Website: https://confidentialcontainers.org/docs/guest-components/ocicrypt-rs/
    - GH: https://github.com/confidential-containers/confidentialcontainers.org/blob/main/content/en/docs/guest-components/ocicrypt-rs/_index.md

**Comment by fitzthum** [comment]
Guest components section has been removed to focus more on users.
